language: node_js
node_js:
  - 12

#services used in this ci-pipeline:
services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  # print the version for logging
  - docker --version 
  #building images:
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend
  #tagging images to dockerhub:
  - docker tag reverseproxy josephmikhail/reverseproxy:v1
  - docker tag udagram-api-user josephmikhail/udagram-api-user:v1
  - docker tag udagram-api-feed josephmikhail/udagram-api-feed:v1
  - docker tag udagram-frontend josephmikhail/udagram-frontend:v1

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  #logging into dockerhub account to push the images:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #pushing all images into dockerhub repos:
  - docker push josephmikhail/reverseproxy:v1
  - docker push josephmikhail/udagram-api-user:v1
  - docker push josephmikhail/udagram-api-feed:v1
  - docker push josephmikhail/udagram-frontend:v1